# Generated by Django 4.2.13 on 2024-07-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('dni', models.TextField()),
                ('nombre', models.TextField()),
                ('apepat', models.TextField()),
                ('apemat', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.TextField()),
                ('estado', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
